### PR TITLE
Authentication

### LINKED ISSUE #8: [FEATURE] User authentication and Sign Up
**Is your feature request related to a problem? Please describe.**
A User can sign up to the app and also login itself without any difficulties

**Describe the solution you'd like**
A simple page where a user can access a protected area.

### PR DESCRIPTION
**Pull request by fabriceyopa**
## Description
This add the User the possibility to register and login to the App. And received a JWT

Fixes #8 

## How Has This Been Tested?
From now we don't have a cool Heroku deployment. So basically you need :
- Create a user with the endpoint HOST/api/register 
- Try to login the user with his information at HOST/api/login

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by fabriceyopa** [comment]
Hi @WilChrist @kouffen can you please check it. I'll soon and a Github Action for auto deploy to Heroku and also try to have a Free Database access

**Review by WilChrist — APPROVED** [review]
@fabriceyopa  Don't forget to provide documentation for api (in order for frontend guys to easily know how to access it)

**Comment by fabriceyopa** [comment]
I'll create a Postman Doc ASAP. Have some issue when Open it on my computer

**Review by kouffen — COMMENTED** [review]
Hi Fabrice, How can i test it localy. there is not a view file for that.

**Comment by fabriceyopa** [comment]
Hi @kouffen it is a JWT authentification API, it means that you should use tools like Postman to send data to that endpoints

**Pull request merged**
