### PR TITLE
Fabriceyopa/issue1

### PR DESCRIPTION
**Pull request by fabriceyopa**
## Description
This is just the Laravel Project bootstrapping. 

Fixes #4 

## How Has This Been Tested?
This is just a default Laravel project. This has been tested by running it local

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by fabriceyopa** [comment]
Nobody here to review this?

**Comment by WilChrist** [comment]
> Nobody here to review this?

@fabriceyopa I already reviewed it. It's to Jean to do it also now.

But if you need it to be merged quick  to be able to move forward, let me know, i'll do it with admin rights

**Review by WilChrist — APPROVED** [review]
For me it's okay, you can move forward

**Comment by fabriceyopa** [comment]
> But if you need it to be merged quick to be able to move forward, let me know, i'll do it with admin rights

Yeah please to that

**Pull request merged**
